services:

    big-boss-lifestyle-api:

        container_name: big-boss-lifestyle-api
        
        image: softwareshinobi/big-boss-lifestyle-api

        depends_on:

           - big-boss-lifestyle-database

        build: 

            context: .

            dockerfile: Dockerfile
    
        restart: always

        ports:

            - "8888:8888"

        environment:

            DB_HOST: big-boss-lifestyle-database

            DB_NAME: big_boss_lifestyle

            DB_USER: big_boss_lifestyle

            DB_PASS: big_boss_lifestyle

    big-boss-lifestyle-database:

        container_name: big-boss-lifestyle-database

        image: mariadb

        ##   volumes:

        ##       - ./.container-volumes/mariadb-server:/var/lib/mysql

        ##   ports:

        ##       - "8886:3306"

        environment:

            MYSQL_ROOT_PASSWORD: aggiepride

            MYSQL_DATABASE: big_boss_lifestyle

            MYSQL_USER: big_boss_lifestyle

            MYSQL_PASSWORD: big_boss_lifestyle

    big-boss-lifestyle-phpmyadmin:

        container_name: big-boss-lifestyle-phpmyadmin

        image: beeyev/phpmyadmin-lightweight

        depends_on:

           - big-boss-lifestyle-database

        links:

           - big-boss-lifestyle-database

        ports:

            - 8885:80

        environment:

            PMA_HOST: big-boss-lifestyle-database

            PMA_PORT: 3306

            PMA_ARBITRARY: 1
